# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getClusters <- function(X, weights, Mean, Sigma) {
    .Call(`_MSGMM_getClusters`, X, weights, Mean, Sigma)
}

getLoglike <- function(X, weights, Mean, Sigma) {
    .Call(`_MSGMM_getLoglike`, X, weights, Mean, Sigma)
}

getLoglikeVals <- function(X, weights, Mean, Sigma) {
    .Call(`_MSGMM_getLoglikeVals`, X, weights, Mean, Sigma)
}

logstep <- function(X, weights, Mean, Sigma, A0, A1, A2) {
    .Call(`_MSGMM_logstep`, X, weights, Mean, Sigma, A0, A1, A2)
}

